name: build site

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: lowply/build-hugo@v0.140.0
      - uses: actions/upload-artifact@v4
        with:
          name: site-public
          retention-days: 1
          path: ./public
          if-no-files-found: error
