name: deploy to pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
